title: Document Understanding eBook
author: Devin Horvay
copyright: "2023"
logo: logo.png
execute:
  execute_notebooks: force
repository:
  url: https://github.com/dhorvay/document-understanding-ebook
html:
  announcement: "Please note: this book is in alpha - it is consistently being updated with content for a v1.0.0 release! 🤗"
  favicon : favicon.ico
  use_issues_button: true
  use_repository_button: true
  extra_footer: |
    All of the material in this book is publicly available under <a href="https://github.com/dhorvay/document-understanding-ebook/blob/main/LICENSE">open source licenses.</a>
bibtex_bibfiles:
  - references.bib
sphinx:
  config:
    bibtex_reference_style: author_year