name: deploy-book

# Only run this when the master branch changes
on:
  push:
    branches:
    - main

env:
  TESSDATA_PREFIX: ~/.local/share/tesseract-ocr/4.00/tessdata_fast

# This job installs dependencies, builds the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install apt packages
      uses: awalsh128/cache-apt-pkgs-action@v1
      with:
        packages: tesseract-ocr libtesseract-dev
        version: 1.0

     - name: Run shell commands
        run: |
          git clone https://github.com/tesseract-ocr/tessdata_fast.git ~/.local/share/tesseract-ocr/4.00/tessdata_fast

    # Install dependencies
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    # Build the book
    - name: Build the book
      run: |
        jupyter-book build src

    # Prepare release tags
    - name: Prepare tag
      id: prepare_tag
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        echo "DEPLOY_TAG_NAME=deploy-${TAG_NAME}" >> "${GITHUB_OUTPUT}"

    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./src/_build/html
        tag_name: ${{ steps.prepare_tag.outputs.DEPLOY_TAG_NAME }}
        tag_message: 'Deployment ${{ github.ref_name }}'